[package]
name = "hashsum"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5", features = ["derive"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
csv = "1.3"
sha2 = "0.10"
sha1 = "0.10"
md-5 = "0.10"
blake3 = "1.5"
walkdir = "2.5"
hex = "0.4"
rayon = "1.10"
memmap2 = "0.9"
crossbeam = "0.8"
indicatif = "0.17"
globset = "0.4"
colored = "2.0"